# Generated by Django 5.0.1 on 2024-01-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hololens2img", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ms1",
            options={"verbose_name": "MS1", "verbose_name_plural": "MS1"},
        ),
        migrations.AlterModelOptions(
            name="ms2",
            options={"verbose_name": "MS2", "verbose_name_plural": "MS2"},
        ),
        migrations.AlterModelOptions(
            name="ms3",
            options={"verbose_name": "MS3", "verbose_name_plural": "MS3"},
        ),
        migrations.AlterModelOptions(
            name="ms4",
            options={"verbose_name": "MS4", "verbose_name_plural": "MS4"},
        ),
        migrations.AlterModelOptions(
            name="ms5",
            options={"verbose_name": "MS5", "verbose_name_plural": "MS5"},
        ),
        migrations.AlterModelOptions(
            name="ms6",
            options={"verbose_name": "MS6", "verbose_name_plural": "MS6"},
        ),
        migrations.AlterModelOptions(
            name="wh",
            options={"verbose_name": "WH", "verbose_name_plural": "WH"},
        ),
        migrations.RemoveField(
            model_name="ms1",
            name="image_data_base64",
        ),
        migrations.RemoveField(
            model_name="ms2",
            name="image_data_base64",
        ),
        migrations.RemoveField(
            model_name="ms3",
            name="image_data_base64",
        ),
        migrations.RemoveField(
            model_name="ms4",
            name="image_data_base64",
        ),
        migrations.RemoveField(
            model_name="ms5",
            name="image_data_base64",
        ),
        migrations.RemoveField(
            model_name="ms6",
            name="image_data_base64",
        ),
        migrations.RemoveField(
            model_name="wh",
            name="image_data_base64",
        ),
        migrations.AddField(
            model_name="ms1",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="ms2",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="ms3",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="ms4",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="ms5",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="ms6",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="wh",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
