# Generated by Django 5.0.1 on 2024-01-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hololens2img", "0002_alter_ms1_options_alter_ms2_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ms1",
            name="label",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="ms2",
            name="label",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="ms3",
            name="label",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="ms4",
            name="label",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="ms5",
            name="label",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="ms6",
            name="label",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="wh",
            name="label",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
